# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6d223a6b951442df211efeed43a9149b016f1a1c3763f7a0d4b0bf11eb90e483ad8142144bb1aea2ae07205b5f50659a9e3fb928f682beecaf36244bd182d42

test:
  secret_key_base: 34863a8ccbfc1c7fd943d0f20ec811211e2bfe1480665022a3f4e7130b566926aa27d45a766b88c826f70db5058b2b1073c6243eb52559f681b2b7371d0ccc61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
